import { Category, Product, Movement, DashboardStats } from "./types";

export const mockCategories: Category[] = [
  { id: "1", nombre: "Mobiliario", descripcion: "Escritorios, sillas y archiveros", color: "#8B5CF6", icono: "Armchair", created_at: "2024-01-01" },
  { id: "2", nombre: "Vehículos", descripcion: "Unidades y flotilla municipal", color: "#3B82F6", icono: "Car", created_at: "2024-01-01" },
  { id: "3", nombre: "Equipo de Cómputo", descripcion: "Laptops, PCs y periféricos", color: "#10B981", icono: "Laptop", created_at: "2024-01-01" },
  { id: "4", nombre: "Equipo de Oficina", descripcion: "Impresoras, copiadoras y consumibles", color: "#F59E0B", icono: "Printer", created_at: "2024-01-01" },
  { id: "5", nombre: "Herramientas y Maquinaria", descripcion: "Maquinaria pesada y herramientas", color: "#EF4444", icono: "Wrench", created_at: "2024-01-01" },
  { id: "6", nombre: "Equipo Audiovisual", descripcion: "Cámaras, proyectores y audio", color: "#EC4899", icono: "VideoCamera", created_at: "2024-01-01" },
];

export const mockProducts: Product[] = [
  {
    id: "1", nombre: "Escritorio ejecutivo de madera", codigo: "MB-001",
    descripcion: "Escritorio ejecutivo con cajonera lateral",
    categoria_id: "1", categoria: mockCategories[0],
    precio_compra: 3200, precio_venta: 2800,
    stock_actual: 18, stock_minimo: 10, stock_maximo: 40,
    unidad: "pieza", proveedor: "Muebles Ejecutivos S.A.",
    estado: "activo", ubicacion: "Palacio Municipal, Piso 2",
    area: "Dirección de Administración",
    created_at: "2024-01-10", updated_at: "2024-12-01",
  },
  {
    id: "2", nombre: "Silla ejecutiva ergonómica", codigo: "MB-002",
    descripcion: "Silla giratoria con soporte lumbar",
    categoria_id: "1", categoria: mockCategories[0],
    precio_compra: 2400, precio_venta: 2100,
    stock_actual: 6, stock_minimo: 15, stock_maximo: 60,
    unidad: "pieza", proveedor: "Muebles Ejecutivos S.A.",
    estado: "bajo_stock", ubicacion: "Palacio Municipal, Piso 1",
    area: "Dirección de Recursos Humanos y Nómina",
    created_at: "2024-01-10", updated_at: "2024-12-01",
  },
  {
    id: "3", nombre: "Archivero metálico 4 gavetas", codigo: "MB-003",
    descripcion: "Archivero de acero con cerradura",
    categoria_id: "1", categoria: mockCategories[0],
    precio_compra: 1800, precio_venta: 1500,
    stock_actual: 0, stock_minimo: 5, stock_maximo: 20,
    unidad: "pieza", proveedor: "Comercializadora de Oficina del Centro",
    estado: "agotado", ubicacion: "Bodega Municipal",
    area: "Dirección del Área Coordinadora de Archivo",
    created_at: "2024-01-10", updated_at: "2024-12-01",
  },
  {
    id: "4", nombre: "Camioneta pick-up Ford Ranger", codigo: "VH-001",
    descripcion: "Unidad doble cabina 4x4",
    categoria_id: "2", categoria: mockCategories[1],
    precio_compra: 620000, precio_venta: 540000,
    stock_actual: 1, stock_minimo: 1, stock_maximo: 1,
    unidad: "unidad", proveedor: "Ford Comercial Puebla",
    estado: "activo", ubicacion: "Corralón Municipal",
    area: "Dirección de Protección Civil y Bomberos",
    created_at: "2024-01-10", updated_at: "2024-12-01",
  },
  {
    id: "5", nombre: "Patrulla Nissan Versa", codigo: "VH-002",
    descripcion: "Unidad de patrullaje equipada",
    categoria_id: "2", categoria: mockCategories[1],
    precio_compra: 380000, precio_venta: 310000,
    stock_actual: 3, stock_minimo: 2, stock_maximo: 5,
    unidad: "unidad", proveedor: "Nissan Flotillas",
    estado: "activo", ubicacion: "Corralón Municipal",
    area: "Secretaría de Seguridad Pública, Tránsito Municipal, Auxilio Vial y Protección Civil",
    created_at: "2024-01-10", updated_at: "2024-12-01",
  },
  {
    id: "6", nombre: "Camión recolector de basura", codigo: "VH-003",
    descripcion: "Compactador de carga trasera",
    categoria_id: "2", categoria: mockCategories[1],
    precio_compra: 1850000, precio_venta: 1600000,
    stock_actual: 1, stock_minimo: 1, stock_maximo: 2,
    unidad: "unidad", proveedor: "Volvo Camiones del Bajío",
    estado: "bajo_stock", ubicacion: "Central Camionera Municipal",
    area: "Dirección de Servicios Públicos y Limpias",
    created_at: "2024-01-10", updated_at: "2024-12-01",
  },
  {
    id: "7", nombre: "Laptop Dell Latitude 5440", codigo: "EC-001",
    descripcion: "Equipo de cómputo portátil corporativo",
    categoria_id: "3", categoria: mockCategories[2],
    precio_compra: 18500, precio_venta: 15200,
    stock_actual: 12, stock_minimo: 10, stock_maximo: 50,
    unidad: "pieza", proveedor: "Grupo TI Soluciones",
    fecha_vencimiento: "2026-08-02",
    estado: "activo", ubicacion: "Palacio Municipal, Piso 3",
    area: "Dirección de Tecnologías de la Información",
    created_at: "2024-01-10", updated_at: "2024-12-01",
  },
  {
    id: "8", nombre: "Computadora de escritorio HP", codigo: "EC-002",
    descripcion: "Equipo de cómputo de escritorio con monitor",
    categoria_id: "3", categoria: mockCategories[2],
    precio_compra: 12000, precio_venta: 9500,
    stock_actual: 4, stock_minimo: 8, stock_maximo: 30,
    unidad: "pieza", proveedor: "Distribuidora de Cómputo Nacional",
    estado: "bajo_stock", ubicacion: "Palacio Municipal, Piso 1",
    area: "Dirección de Catastro",
    created_at: "2024-01-10", updated_at: "2024-12-01",
  },
  {
    id: "9", nombre: "Impresora multifuncional Epson", codigo: "EO-001",
    descripcion: "Impresora, escáner y copiado a color",
    categoria_id: "4", categoria: mockCategories[3],
    precio_compra: 8500, precio_venta: 6800,
    stock_actual: 2, stock_minimo: 3, stock_maximo: 10,
    unidad: "pieza", proveedor: "Office Depot Gobierno",
    fecha_vencimiento: "2026-08-01",
    estado: "bajo_stock", ubicacion: "Palacio Municipal, Planta Baja",
    area: "Unidad Central de Correspondencia",
    created_at: "2024-01-10", updated_at: "2024-12-01",
  },
  {
    id: "10", nombre: "Fotocopiadora Xerox industrial", codigo: "EO-002",
    descripcion: "Copiado de alto volumen",
    categoria_id: "4", categoria: mockCategories[3],
    precio_compra: 45000, precio_venta: 32000,
    stock_actual: 0, stock_minimo: 2, stock_maximo: 6,
    unidad: "pieza", proveedor: "Xerox México",
    estado: "agotado", ubicacion: "Palacio Municipal, Piso 1",
    area: "Dirección de Gobierno",
    created_at: "2024-01-10", updated_at: "2024-12-01",
  },
  {
    id: "11", nombre: "Retroexcavadora CAT 420", codigo: "HM-001",
    descripcion: "Maquinaria pesada para obra pública",
    categoria_id: "5", categoria: mockCategories[4],
    precio_compra: 2400000, precio_venta: 2100000,
    stock_actual: 1, stock_minimo: 1, stock_maximo: 1,
    unidad: "unidad", proveedor: "Maquinaria Pesada CAT Puebla",
    estado: "activo", ubicacion: "Almacén de Obras Públicas",
    area: "Dirección de Obras Públicas",
    created_at: "2024-01-10", updated_at: "2024-12-01",
  },
  {
    id: "12", nombre: "Podadora industrial autopropulsada", codigo: "HM-002",
    descripcion: "Equipo para mantenimiento de áreas verdes",
    categoria_id: "5", categoria: mockCategories[4],
    precio_compra: 15500, precio_venta: 12800,
    stock_actual: 5, stock_minimo: 4, stock_maximo: 15,
    unidad: "unidad", proveedor: "Jardinería y Equipos S.A.",
    estado: "activo", ubicacion: "Bodega Municipal",
    area: "Dirección de Servicios Municipales",
    created_at: "2024-01-10", updated_at: "2024-12-01",
  },
  {
    id: "13", nombre: "Cámara de videovigilancia PTZ", codigo: "AV-001",
    descripcion: "Cámara motorizada para eventos y monitoreo",
    categoria_id: "6", categoria: mockCategories[5],
    precio_compra: 4200, precio_venta: 3600,
    stock_actual: 22, stock_minimo: 10, stock_maximo: 40,
    unidad: "pieza", proveedor: "Seguritech Videovigilancia",
    estado: "activo", ubicacion: "Bodega Municipal",
    area: "Dirección de Logística y Eventos",
    created_at: "2024-01-10", updated_at: "2024-12-01",
  },
  {
    id: "14", nombre: "Proyector Epson PowerLite", codigo: "AV-002",
    descripcion: "Proyector para salas de juntas y eventos",
    categoria_id: "6", categoria: mockCategories[5],
    precio_compra: 22000, precio_venta: 17500,
    stock_actual: 3, stock_minimo: 5, stock_maximo: 15,
    unidad: "pieza", proveedor: "Proyecta AV México",
    fecha_vencimiento: "2026-08-03",
    estado: "bajo_stock", ubicacion: "Palacio Municipal, Piso 2",
    area: "Dirección de Comunicación Social y Marketing Digital",
    created_at: "2024-01-10", updated_at: "2024-12-01",
  },
];

export const mockMovements: Movement[] = [
  {
    id: "1", producto_id: "7", producto: mockProducts[6],
    tipo: "entrada", cantidad: 5,
    stock_anterior: 7, stock_nuevo: 12,
    motivo: "Alta por compra", referencia: "OC-2026-014",
    usuario_id: "u1", usuario_nombre: "Admin",
    created_at: "2026-07-29T09:00:00",
  },
  {
    id: "2", producto_id: "2", producto: mockProducts[1],
    tipo: "salida", cantidad: 9,
    stock_anterior: 15, stock_nuevo: 6,
    motivo: "Reasignación entre direcciones", referencia: "RES-2026-031",
    usuario_id: "u1", usuario_nombre: "Admin",
    created_at: "2026-07-29T10:30:00",
  },
  {
    id: "3", producto_id: "10", producto: mockProducts[9],
    tipo: "salida", cantidad: 2,
    stock_anterior: 2, stock_nuevo: 0,
    motivo: "Baja por obsolescencia", referencia: "BAJ-2026-006",
    usuario_id: "u2", usuario_nombre: "Empleado 1",
    created_at: "2026-07-29T11:15:00",
  },
  {
    id: "4", producto_id: "13", producto: mockProducts[12],
    tipo: "ajuste", cantidad: 4,
    stock_anterior: 18, stock_nuevo: 22,
    motivo: "Corrección de inventario físico", referencia: "AJU-2026-011",
    usuario_id: "u1", usuario_nombre: "Admin",
    created_at: "2026-07-28T16:00:00",
  },
];

export function productsByArea(areaName: string): Product[] {
  return mockProducts.filter((p) => p.area === areaName);
}

export const mockStats: DashboardStats = {
  total_productos: 14,
  productos_activos: 7,
  productos_bajo_stock: 5,
  productos_agotados: 2,
  productos_vencidos: 0,
  valor_total_inventario: 5662700,
  movimientos_hoy: 3,
  categorias: 6,
};
